name:                micromarshall
version:             0.1.0.0
github:              "githubuser/micromarshall"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/micromarshall#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- hmpfr
- MemoTrie
- hscolour

default-extensions:
  - TypeOperators

library:
  source-dirs: src

executables:
  runexamples:
    main:             test/RunExamples.hs
    source-dirs:      src
  demo:
    main:             test/Demo.hs
    source-dirs:      src

ghc-options:      -O
